/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai_tap_lon_java;



/**
 *
 * @author seape
 */
public class chuc_nang_user extends javax.swing.JFrame {

    /**
     * Creates new form chuc_nang_user
     */
    public chuc_nang_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        emvatrinh_button = new javax.swing.JButton();
        jurrasic_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nobita_button = new javax.swing.JButton();
        blackphone_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lightyear_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        topgun_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        maika_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        maguong_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        broker_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        thor_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 255, 51));
        kGradientPanel1.setkGradientFocus(-30);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emvatrinh_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/em_va_trinh_button.png"))); // NOI18N
        emvatrinh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emvatrinh_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(emvatrinh_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 190, 280));

        jurrasic_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/jurassic_button.png"))); // NOI18N
        jurrasic_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurrasic_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jurrasic_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("EM VÀ TRỊNH");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("JURASSIC WORLD");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 20));

        nobita_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/doraemon.png"))); // NOI18N
        nobita_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobita_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nobita_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 190, 280));

        blackphone_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/blackphone.png"))); // NOI18N
        blackphone_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackphone_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(blackphone_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 190, 280));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 102));
        jLabel3.setText("<html>DORAEMON: NOBITA<br/>LITTLE STAR WAR</html>");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("THE BLACK PHONE");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 140, -1));

        lightyear_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/lightyear.png"))); // NOI18N
        lightyear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightyear_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(lightyear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 190, 280));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("LIGHT YEAR");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, -1, -1));

        topgun_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/topgun.png"))); // NOI18N
        topgun_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topgun_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(topgun_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 180, 280));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 102));
        jLabel6.setText("TOP GUN MAVERICK");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, -1, -1));

        maika_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/MAIKA.png"))); // NOI18N
        maika_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maika_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(maika_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 190, 280));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 102));
        jLabel7.setText("MAIKA");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 690, 60, -1));

        maguong_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/MAGUONG.png"))); // NOI18N
        maguong_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maguong_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(maguong_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 190, 280));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 51));
        jLabel8.setText("KUNTILANAK 3");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        broker_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/BROKER.png"))); // NOI18N
        broker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broker_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(broker_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 190, 280));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 102));
        jLabel9.setText("BROKER");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, -1, -1));

        thor_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bai_tap_lon_java/icon_baitap/thor.png"))); // NOI18N
        thor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thor_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(thor_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 190, 280));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 102));
        jLabel10.setText("<html>THOR: LOVE<br/> AND THUNDER</html>");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 680, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Hãy trải nghiệm!!!");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 190, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jurrasic_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurrasic_buttonActionPerformed
        // TODO add your handling code here:
        jurassic_form jura = new jurassic_form();
        jura.setVisible(true);
        
        
    }//GEN-LAST:event_jurrasic_buttonActionPerformed

    private void blackphone_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackphone_buttonActionPerformed
        // TODO add your handling code here:
        blackphone_form blphone = new blackphone_form();
        blphone.setVisible(true);
    }//GEN-LAST:event_blackphone_buttonActionPerformed

    private void emvatrinh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emvatrinh_buttonActionPerformed
        // TODO add your handling code here:
        emvatrinh_form evatrinh = new emvatrinh_form();
        evatrinh.setVisible(true);
        
    }//GEN-LAST:event_emvatrinh_buttonActionPerformed

    private void nobita_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobita_buttonActionPerformed
        // TODO add your handling code here:
        nobita_form nobi = new nobita_form();
        nobi.setVisible(true);
    }//GEN-LAST:event_nobita_buttonActionPerformed

    private void lightyear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightyear_buttonActionPerformed
        // TODO add your handling code here:
        lightyear_form liyear = new lightyear_form();
        liyear.setVisible(true);      
    }//GEN-LAST:event_lightyear_buttonActionPerformed

    private void topgun_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topgun_buttonActionPerformed
        // TODO add your handling code here:
        topgunmaverick_form tgmave = new topgunmaverick_form();
        tgmave.setVisible(true);
    }//GEN-LAST:event_topgun_buttonActionPerformed

    private void maika_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maika_buttonActionPerformed
        // TODO add your handling code here:
        maika_form maka = new maika_form();
        maka.setVisible(true);
    }//GEN-LAST:event_maika_buttonActionPerformed

    private void maguong_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maguong_buttonActionPerformed
        // TODO add your handling code here:
        maguong_form mguong = new maguong_form();
        mguong.setVisible(true);
    }//GEN-LAST:event_maguong_buttonActionPerformed

    private void broker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broker_buttonActionPerformed
        // TODO add your handling code here:
        broker_form bro = new broker_form();
        bro.setVisible(true);
    }//GEN-LAST:event_broker_buttonActionPerformed

    private void thor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thor_buttonActionPerformed
        // TODO add your handling code here:
        thor_form th = new thor_form();
        th.setVisible(true);
    }//GEN-LAST:event_thor_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chuc_nang_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chuc_nang_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chuc_nang_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chuc_nang_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chuc_nang_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackphone_button;
    private javax.swing.JButton broker_button;
    private javax.swing.JButton emvatrinh_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jurrasic_button;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JButton lightyear_button;
    private javax.swing.JButton maguong_button;
    private javax.swing.JButton maika_button;
    private javax.swing.JButton nobita_button;
    private javax.swing.JButton thor_button;
    private javax.swing.JButton topgun_button;
    // End of variables declaration//GEN-END:variables
}
