/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai_tap_lon_java;

import java.util.Date;
import javax.swing.JOptionPane;
import ket_noi_sql.InsertMySQL;
/**
 *
 * @author seape
 */
public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hoten_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diachi_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        taikhoan_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sdt_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mk_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        xacnhan_text = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(-10);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VUI LÒNG");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐIỀN THÔNG TIN BÊN DƯỚI");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 250, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HỌ VÀ TÊN");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));
        kGradientPanel1.add(hoten_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 170, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ĐỊA CHỈ");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 50, -1));
        kGradientPanel1.add(diachi_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 170, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SỐ ĐIỆN THOẠI");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));
        kGradientPanel1.add(taikhoan_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 170, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TÀI KHOẢN");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));
        kGradientPanel1.add(sdt_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 170, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MẬT KHẨU");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));
        kGradientPanel1.add(mk_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 170, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("XÁC NHẬN MẬT KHẨU");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, 20));
        kGradientPanel1.add(xacnhan_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 170, 30));

        kButton1.setText("Đăng ký");
        kButton1.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton1.setkForeGround(new java.awt.Color(204, 255, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton1.setkHoverForeGround(new java.awt.Color(204, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        kButton1.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NGÀY SINH");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));
        kGradientPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 170, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        if(mk_text.getText().equals(xacnhan_text.getText())) {
            String hoten = hoten_text.getText();
            String diachi = diachi_text.getText();
            String mk = mk_text.getText();
            String tk = taikhoan_text.getText();
            String sdt = sdt_text.getText();
            Date ngaysinh = jDateChooser1.getDate();
            xacnhan_dangky xndky = new xacnhan_dangky();
            java.sql.Date sqlDate = new java.sql.Date(ngaysinh.getTime());
            InsertMySQL.insertUser(tk, mk, hoten, diachi, sqlDate, sdt);
            xndky.setVisible(true);}
        else {
            JOptionPane.showMessageDialog(null, "Hãy kiểm tra lại mật khẩu");
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diachi_text;
    private javax.swing.JTextField hoten_text;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField mk_text;
    private javax.swing.JTextField sdt_text;
    private javax.swing.JTextField taikhoan_text;
    private javax.swing.JTextField xacnhan_text;
    // End of variables declaration//GEN-END:variables
}
